AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation Template for Earth Watcher CloudFront Distribution

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: "The environment for the CloudFront distribution."

  DeploymentRoleARN:
    Type: String
    Description: "ARN of the IAM role for deployment."

Resources:
  UIS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "earth-watcher-ui-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  UIS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UIS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref DeploymentRoleARN
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub "${UIS3Bucket.Arn}/*"
              - !Sub "${UIS3Bucket.Arn}"
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E1CXPOQH50XLNI"
            Action: s3:GetObject
            Resource: !Sub "${UIS3Bucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CallerReference: !Sub "${AWS::StackName}-${Environment}-${AWS::Region}"
        Origins:
          - Id: !Sub "earth-watcher-dashboard-${Environment}.s3.${AWS::Region}.amazonaws.com"
            DomainName: !Sub "earth-watcher-dashboard-${Environment}.s3.${AWS::Region}.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: "origin-access-identity/cloudfront/E1CXPOQH50XLNI"
        DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          TargetOriginId: !Sub "${UIS3Bucket}-origin"
          ViewerProtocolPolicy: "allow-all"
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
        Enabled: true
        HttpVersion: "http2"
        IsIPV6Enabled: true
        PriceClass: "PriceClass_All"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  UIS3BucketName:
    Description: "S3 Bucket name"
    Value: !Ref UIS3Bucket
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
  CloudFrontDomainName:
    Description: "CloudFront Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
