AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for the Earth Watcher UI

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: "The environment for the UI."

  DeploymentRoleARN:
    Type: String
    Description: "ARN of the IAM role for deployment."

Resources:
  UIS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "earth-watcher-ui-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  UIS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UIS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref DeploymentRoleARN
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub "${UIS3Bucket.Arn}/*"
              - !Sub "${UIS3Bucket.Arn}"
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E1CXPOQH50XLNI"
            Action: s3:GetObject
            Resource: !Sub "${UIS3Bucket.Arn}/*"

Outputs:
  UIS3BucketName:
    Description: "Bucket name"
    Value: !Ref UIS3Bucket
